### ISSUE TITLE
[all-the-mods-6] Server does not build with mod files as expected

### ISSUE THREAD

**Issue by sharknoon** [curseforge-docker/modpack-servers#1]
First of all I want to thank you for making a docker image for These modpacks. Althaugh I cant get it running. I start the container with `docker run --env EULA=true -p 25565:25565 curseforge/all-the-mods-6:1.4.1` and it starts the container but if I try to join, it says that the modlist is incorrect. If I look into the mods folder, it is empty. 
Also I would highly appreciate some documentation.

Thanks for your good work

Kind regards

Sharknoon

**Comment by artheus** [comment]
@Sharknoon Hi. Thank you for this. I will look into this.

**Comment by artheus** [comment]
@Sharknoon Seems I used an incorrect download URL for downloading server files. I have now re-triggered the build job, and 1.4.1 should now be working.

**Comment by artheus** [comment]
@Sharknoon I tested the newly build image locally and was able to run the server with mods.
Do a `docker pull curseforge/all-the-mods-6:1.4.1` and you should be able to start and run the server correctly.

**Comment by artheus** [comment]
@Sharknoon I am sorry, it seems that I used the client files there. Please test if this works for you.
The All-the-mods 6 modpack does not provide a standard type of modpack server zip. It only includes a yaml config and some shell scripts.

**Comment by sharknoon** [comment]
@artheus Thank you for your work. I deleted the old image, pulled the new one and unfortunately the server wont event start. It produces a `java.lang.Exception: Mod Loading has failed`, caused by the mod `ding`.

When using the starter script from the mod makers (`startserver.sh`) we need to make sure to create a eula.txt beforehand, because the starter script requires the user to enter a `true` from the sysin (console) during the first start of the script [sourcecode](https://github.com/BloodyMods/ServerStarter/blob/be94470e4b51e06660d9d973af5484632d31d355/src/main/kotlin/atm/bloodworkxgaming/serverstarter/LoaderManager.kt#L63-L100).

When using the script to install the server during the build phase, it will simply stop at the input (not fully installed). Also the script starts the server after the installation automatically (not wanted during build time). Therefore I would suggest copying the script to the image during build time and during the run time check for the EULA environment variable and create a eula.txt (otherwise exit!). Now the script shouldn't ask for eula input, installs the server if it isn't already installed and starts it.

**Comment by artheus** [comment]
@Sharknoon My goal here is to build all mod packs with the same base. But obviously that is proving to be quite impossible.

**Comment by artheus** [comment]
@Sharknoon Would you like to become a part of this project? Maybe we could co-operate and come up with a nice plan for this, together?

**Comment by artheus** [comment]
@Sharknoon Ah I get it now. What their server-files do is they download the client files, but with a "project ignore"-list.
Because e.g. Ding is a client-only mod, and does not work on the server side.
I'll try to make some changes to the prepare script to attempt to fix that.

**Comment by artheus** [comment]
@Sharknoon Now I have rebuild the `all-the-mods-6:1.4.1` image, please to a `docker pull` again and start it.
I have tested locally, and it starts all the way, and is joinable by the version 1.4.1 client.

**Comment by artheus** [comment]
For reference, this is how I start servers

First I create a run directory, where I create some files and folders

```shell
mkdir atm6
cd atm6

mkdir {config,world,backups}
touch {server.properties,whitelist.json,ops.json}
```

Then I start the server in docker using this script:

```shell
#!/bin/bash
# start.sh

docker run -d --name atm6 \
           -p 25565:25565 \
           -e EULA=true \
           -v $PWD/config:/minecraft/config \
           -v $PWD/world:/minecraft/world \
           -v $PWD/backups:/minecraft/backups \
           -v $PWD/server.properties:/minecraft/server.properties \
           -v $PWD/ops.json:/minecraft/ops.json \
           -v $PWD/whitelist.json:/minecraft/whitelist.json \
           --restart always \
           curseforge/all-the-mods-6:1.4.1
```

This is the easy way to get started with a Linux host and docker. I am aiming for a K8s setup with persistent volumes etc.

**Comment by sharknoon** [comment]
> 
> 
> @Sharknoon Would you like to become a part of this project? Maybe we could co-operate and come up with a nice plan for this, together?

Hi @artheus,
yes, I would like to take part in building modpack server images and keep them up-to-date :) How can I join?

**Comment by artheus** [comment]
@Sharknoon Sent you a Discord invite on your email

**Comment by j-gow** [comment]
Hi, I had issues using the script above (Artheus') so had to change it, thought I'd share mine just in case it helps anybody browsing.

```
mkdir /media/james/storage/minecraft
cd /media/james/storage/minecraft

mkdir {config,world,backups}
touch {server.properties,whitelist.json,ops.json}
```

```
docker run -d --name minecraft-server \
           -p 25565:25565 \
           -e EULA=true \
           -v /media/james/storage/minecraft/config:/config \
           -v /media/james/storage/minecraft/world:/world \
           -v /media/james/storage/minecraft/backups:/backups \
           -v /media/james/storage/minecraft/server.properties:/server.properties \
           -v /media/james/storage/minecraft/ops.json:/ops.json \
           -v /media/james/storage/minecraft/whitelist.json:/whitelist.json \
           --restart always \
           curseforge/all-the-mods-6:1.4.1
```
