### ISSUE TITLE
Not an issue, but might help for the documentation on the homepage

### ISSUE THREAD

**Issue by wjwnz** [curseforge-docker/modpack-servers#10]
I have All The Mods 6 and RLCraft working in docker on a vanilla Ubuntu 20.04.2 LTS
--------------- curseforge/all-the-mods-6
docker run -d -it -v atm-volume:/data --name curseforge-atm -p 192.168.1.11:25565:25565  -e EULA=true curseforge/all-the-mods-6
---------------- curseforge/rlcraft:2.8.2
docker run -d -it -v rlc-volume:/data --name curseforge-rlc -p 192.168.1.99:25565:25565 -e EULA=true curseforge/rlcraft:2.8.2

You will need a significant amount of RAM and CPU.  I have an Intel I7 and it needed 4 cores and 8GB RAM for these two to run reliably together.

**Comment by artheus** [comment]
@wjwnz This is a good idea, you are very welcome to make Pull requests to our README.md!

**Comment by artheus** [comment]
@wjwnz I've added documentation about resource handling in the Readme.
Please re-open this issue, if you consider my change to be insufficient.
