### ISSUE TITLE
Mod Mismatch & Data not being written to volume

### ISSUE THREAD

**Issue by Shinku443** [curseforge-docker/modpack-servers#9]
Hey, so I've gotten vanilla minecraft, FTB (from your other repo), and a couple spigot servers hosted within docker that work fine. But I'm getting an issue where I'm using all-the-mods 6 version 1.15.0 within docker, and trying to connect locally with a freshly installed all-the-mods 6 version 1.15.0 client via curseforge client. When highlighting my server within my saved minecraft servers theres an X saying "Incompatible FML modded server. Server network message list is not compatible". and when I try to join it says "Connection closed - mismatched mod channel list". I haven't touched the mods client/server side at all.  I tried recreating the docker image with volume written from /data but there's nothing in it so I'm not sure whats happening.

**Comment by artheus** [comment]
@Sharknoon Were you able to connect with a client when you set up your all-the-mods 6 server?

**Comment by sharknoon** [comment]
@Shinku443 I am sorry for your container not working properly. We were in the middle of a refactoring, so some images have not been tested.

But the good news are, that the refactoring is done. Please have a look at [the dedicated repo for All the Mods 6](https://github.com/curseforge-docker/all-the-mods-6). There you will find all further all-the-mods-6 images. These images there are tested.

Have fun :)

**Comment by Shinku443** [comment]
I wasn't able to connect from my client to server at all no, also tried the RLCraft image and while I am able to start the server (and connect), The volumes aren't pulling the right data from the minecraft server. I poked around and tried to pull in by grabbing the absolute path of /minecraft/config, /minecraft/world but  when i try to connect i get "fatally missing registry entries" (when config is pulled specifically)
